const path = require('path');

/**
 * Resolves `fileName` inside `baseDir` and verifies the resulting absolute
 * path is actually contained within `baseDir`. This guards against path
 * traversal even though callers only ever pass filenames generated by our
 * own upload middleware (uuid + whitelisted extension), keeping file access
 * strictly scoped to the configured upload directory.
 */
function resolveSafePath(baseDir, fileName) {
  const resolvedBase = path.resolve(baseDir);
  const resolvedPath = path.resolve(resolvedBase, path.basename(fileName));

  if (resolvedPath !== resolvedBase && !resolvedPath.startsWith(resolvedBase + path.sep)) {
    throw new Error('Resolved path escapes the allowed base directory.');
  }

  return resolvedPath;
}

module.exports = { resolveSafePath };
